---
title: "Elements of Matrix Algebra"
author: "Yannick Hoga"
date: "Winter 2024"
fontsize: 9pt
output:
   runidue::lectureslides:
      keep_tex: true
      lang: "en"
      logo: false
      towers: true
      footerstyle: "colored"
bibliography: Resources/references.bib
csl: Resources/apa.csl

---

```{r setup, include=FALSE}
#options(tinytext.clean=FALSE)
pkgs <- list("grid", "plotrix", "gtools", "lubridate", "readxl", "momentfit",
             "MASS", "gridExtra", "scales", "foreign", "stargazer",
             "knitr", "highr","lmtest", "sandwich")
invisible(lapply(pkgs, library, character.only = T))
```


## Introduction

The material covered here may be found in numerous appendices of econometrics textbooks. 
We will only give definitions and results relevant to econometrics (you will be asked to verify some in the exercises).
For more, see, e.g.,

- Rao and Rao (1998) *Matrix Algebra and Its Applications to Statistics and Econometrics*. World Scientific, 1st ed.
  - Has the necessary background on linear algebra.
- Magnus and Neudecker (2019) *Matrix Differential Calculus with Applications in Statistics and Econometrics*. Wiley, 3rd ed.
  - The title summarizes it aptly.
- Lütkepohl (1996) *Handbook of Matrices*. Wiley, 3rd ed.
  - Has a lot more results for ready reference.


## Definitions, Notation, Terminology

\defn[Matrix]
A $(m \times n)$ \hil{matrix} $\mA$ is an array of numbers:
\[
\mA=\left(%
\begin{array}{ccc}
  a_{11} & \cdots & a_{1n} \\
  \vdots & \ddots & \vdots \\
  a_{m1} & \cdots & a_{mn}
\end{array}%
\right)
\]
Alternative notation: $\mA\;(m \times n)$, $\mA=[a_{ij}]\;(m\times n)$.
\medskip

$m$ and $n$ are positive integers denoting the \hil{row dimension} and the \hil{column dimension},
respectively, $(m \times n)$ is the \hil{dimension} or order of $\mA$.\medskip

For our purposes, the $a_{ij},\;i = 1,\ldots, m,\;j = 1,\ldots, n$, are elements of
$\mathbb{R}$.\medskip

As such, $\mA$ can be viewed as a linear mapping $\mA:\mathbb{R}^n\to\mathbb{R}^m$.
\enddefn


##

\defn[Block Matrix]
\[
\mA= \left(%
\begin{array}{ccc}
  \mA_{11} & \cdots & \mA_{1n} \\
  \vdots & \ddots & \vdots \\
  \mA_{m1} & \cdots & \mA_{mn} \\
\end{array}%
\right)
\]
Here, the $\mA_{ij}$ are $(m_i \times n_j)$ submatrices of $\mA$. A matrix written in terms of submatrices rather than individual elements is often called a \hil{partitioned matrix} or a
\hil{block matrix}.
\enddefn


##

\defn[Special Matrices and Elements]
A matrix $\mA\;(m \times m)$ having the same number of rows and columns is a \hil{square} or \hil{quadratic matrix}.\medskip

The elements $a_{ii}, \;i= 1,\ldots,m,$ constitute its \hil{principal diagonal}.\medskip

If $a_{ii}=1$ for $i = 1,\ldots, m$, and $a_{ij}= 0$ for $i\neq j$ is an ($m \times m)$ \hil{identity matrix}, denoted $\mI_m$.\medskip

A $(1\times n)$ matrix $\va$ is an $n$-dimensional \hil{row vector} or $(1\times n)$ vector.\medskip

An $(m \times 1)$ matrix $\vb$ is an $m$-dimensional \hil{column vector}.
\enddefn


##


\defn[Trace and Transpose]
The \hil{trace} of $\mA$ is defined as
\[
  \tr(\mA) = \sum_{i=1}^ma_{ii}
\]
The \hil{transpose} of $\mA\;(m \times n)$ is defined as
\[
\mA^\top=\left(%
\begin{array}{ccc}
  a_{11} & \cdots & a_{1n} \\
  \vdots & \ddots & \vdots \\
  a_{m1} & \cdots & a_{mn}
\end{array}%
\right)^\top=\left(%
\begin{array}{ccc}
  a_{11} & \cdots & a_{m1} \\
  \vdots & \ddots & \vdots \\
  a_{1n} & \cdots & a_{mn}
\end{array}%
\right)
\]
$\mA^\top$ is $(n \times m)$. That is, the rows of $\mA$ are the columns of $\mA^\top$.
\enddefn


##

\defn[Determinant]
The \hil{determinant} of $\mA\;(m\times m)$
\begin{eqnarray*}
 \det(\mA) =|\mA|&=& a_{i1} \textrm{cof}(a_{i1})+\ldots+
a_{im}\textrm{cof}(a_{im}) \\&=&
a_{1j}\textrm{cof}(a_{1j})+\ldots+ a_{mj}\textrm{cof}(a_{mj}),
\end{eqnarray*}
where $\textrm{cof}(a_{ij})=(-1)^{i+j}\textrm{minor}(a_{ij})$ and
\[
\textrm{minor}(a_{ij})=\left|%
\begin{array}{cccccc}
  a_{1,1} & \cdots & a_{1,j-1} &  a_{1,j+1} & \cdots &  a_{1,m}\\
  \vdots &  & \vdots & \vdots &  & \vdots \\
  a_{i-1,1} & \cdots & a_{i-1,j-1} & a_{i-1,j+1} & \cdots & a_{i-1,m} \\
   a_{i+1,1} & \cdots & a_{i+1,j-1} & a_{i+1,j+1} & \cdots & a_{i+1,m} \\
  \vdots &  & \vdots & \vdots &  & \vdots \\
  a_{m,1} & \cdots & a_{m,j-1} & a_{m,j+1} & \cdots & a_{m,m} \\
\end{array}%
\right|
\]
\enddefn


##


\defn[Inverses]
For $\mA \;(m \times m)$ with $\det(\mA)\neq 0$, the \hil{inverse} of $\mA$ is the unique $(m \times m)$ matrix $\mA^{-1}$ satisfying $\mA\mA^{-1} = \mA^{-1}\mA = \mI_m$.\medskip

An $(n \times m)$ matrix $\mA^-$ is a \hil{generalized inverse} of the $(m \times n)$ matrix $\mA$ if it satisfies $\mA\mA^-\mA = \mA$. $\mA^-$ is generally not unique.\medskip

The $(n \times m)$ matrix $\mA^+$ is the \hil{Moore--Penrose (generalized) inverse} of the $(m \times
n)$ matrix $\mA$ if it satisfies
\begin{itemize} 
  \item $\mA\mA^+\mA = \mA$,
  \item $\mA^+\mA\mA^+ = \mA^+$, 
  \item $(\mA\mA^+)^\top = \mA\mA^+$, 
  \item $(\mA^+\mA)^\top = \mA^+\mA$ .
\end{itemize}
$\mA^+$ exists and is unique.
\enddefn


##

\defn[Certain Matrix Products]
\hil{Power} of a matrix $\mA\;(m \times m)$:
\[ \mA^i=\begin{cases} \prod_{j=1}^i \mA =
\underbrace{\mA\times
\cdots \times \mA}_{i \textrm{ times}} & \text{for positive integers, }i\in\mathbb{Z}^+ \\[.5cm] \mI_m &\textrm{for } i=0 \\[.5cm]
(\prod_{j=1}^{-i} \mA)^{-1} & \text{for }i\in\mathbb{Z}^-,
\text{if } \det(\mA)\neq 0
\end{cases}
\]
The $(m \times m)$ matrix $\mA^{1/2}$ is a \hil{square root} of the $(m \times m)$ matrix $\mA$ if
$\mA^{1/2}\mA^{1/2}=\mA$.
\enddefn


## 

\defn[Vectorization]
The \hil{vectorization} of $\mA\;(m \times n)$ is
\[
\vec(\mA)=\left(%
\begin{array}{c}
  a_{11} \\
  \vdots \\
  a_{m1} \\
  a_{12} \\
  \vdots \\
  a_{m2} \\
  \vdots \\
  a_{1n} \\
  \vdots \\
  a_{mn} \\
\end{array}%
\right)\;(mn \times 1) \] 
That is, vec stacks the columns of $\mA$ in a column vector.
\enddefn


## 

\defn[Some Matrix Properties]\zlabel{matrixproperties}
\begin{enumerate}
\item\zlabel{it:9.1} An $(m \times m)$ matrix with $\mA = \mA^\top$ is \hil{symmetric}.

\item\zlabel{it:9.2} An $(m \times m)$ matrix $\mA$ is \hil{idempotent} if $\mA^2 = \mA$.

\item\zlabel{it:9.3} An $(m \times m)$ matrix $\mA$ is \hil{nonsingular} or \hil{invertible} or \hil{regular} if $\det(\mA) \neq 0$ and thus $\mA^{-1}$ exists.

\item\zlabel{it:9.4} An $(m \times m)$ matrix $\mA$ is \hil{orthogonal} if $\mA$ is nonsingular and $\mA^\top = \mA^{-1}$.

\end{enumerate}
\enddefn


## Concepts Related to Individual Matrices

\defn[Definiteness]\zlabel{Definiteness}
A symmetric $(m \times m)$ matrix $\mA$ is
\begin{itemize}

\item \hil{positive definite} if $\vx^\top \mA\vx > 0$ for all $(m\times 1)$ vectors $\vx \neq \vzero$ 

\item \hil{positive semidefinite} if $\vx^\top \mA\vx \geqslant 0$ for all $(m \times 1)$ vectors $\vx$

\item \hil{negative definite} if $\vx^\top \mA\vx < 0$ for all $(m\times 1)$ vectors $\vx \neq \vzero$

\item \hil{negative semidefinite} if $\vx^\top \mA\vx \leqslant 0$ for all $(m \times 1)$ vectors $\vx$

\item \hil{indefinite} if there exist $(m \times 1)$ vectors $\vx$ and $\vy$ such that $\vx^\top \mA\vx > 0$ and $\vy^\top \mA\vy < 0 $.

\end{itemize}
\enddefn


##

\defn[Triangular Matrices]
An $(m \times m)$ matrix
\[
\mA=\left(%
\begin{array}{cccc}
  a_{11} & 0 & \cdots & 0 \\
  \vdots & \ddots & \ddots & \vdots \\
  \vdots &  & \ddots & 0 \\
  a_{m1} & \cdots & \cdots & a_{mm} \\
\end{array}%
\right)
\] 
is \hil{lower triangular}.\medskip

A matrix $\mA\;(m\times m)$ that is both upper and lower triangular is a \hil{diagonal matrix}, denoted $\mA = \diag(a_{11},\ldots,a_{mm})$.
\enddefn


## Further Concepts

\defn\zlabel{linindep}
The $m$-dimensional row or column vectors $\vx_1,\ldots,\vx_k$ are \hil{linearly independent} if, for scalars $c_1,\ldots,c_k$, $c_1\vx_1+\ldots+c_k \vx_k = \vzero$ implies $c_1,\ldots,c_k = 0$.
\enddefn

\defn
The \hil{rank} of $\mA\;(m\times n)$, denoted $\rk(\mA)$, is the maximum number of linearly independent rows or columns of $\mA$.
\enddefn

\defn\zlabel{quadrform}
Given a symmetric $(m \times m)$ matrix $\mA$, the function $Q: \mathbb{R}^m\rightarrow\mathbb{R}$ defined by $Q(\vx) = \vx^\top \mA\vx$ is called a \hil{quadratic form}.
\enddefn

\defn
The polynomial in $\mA$ given by $\det(\lambda\,\mI_m - \mA)$ is the \hil{characteristic polynomial} of the $(m \times m)$ matrix $\mA$.
\enddefn


##

\defn[Eigenvalues and Eigenvectors]
The \hil{eigenvalues} of an $(m \times m)$ matrix $\mA$ are the roots of the characteristic polynomial of $\mA$.\medskip

(Note that eigenvalues can be complex depending on the polynomial.)\medskip

An $(m \times 1)$ vector $\vv \neq \vzero$ satisfying $\mA\vv = \lambda \vv$, where $\lambda$ is an eigenvalue of $\mA$, is an \hil{eigenvector} corresponding to the eigenvalue $\lambda$.
\enddefn


## Kronecker Product

\defn
The \hil{Kronecker product} of $\mA\;(m\times n)$ and $\mB\;(p\times q)$ is defined as the $(mp \times nq)$ matrix
\[
  \mA\otimes \mB=\left(%
\begin{array}{ccc}
  a_{11}\mB & \cdots & a_{1n}\mB \\
  \vdots & \ddots & \vdots \\
  a_{m1}\mB & \cdots & a_{mn}\mB
\end{array}%
\right)
\] 
\enddefn


## Operations Relating Matrices

\defn
\begin{enumerate} 

\item \hil{Addition:} $\mA \;(m \times n),\;\mB\;(m \times n): \mA+\mB= [a_{ij}+b_{ij}]\;(m \times n)$ 

\item $\mA,\mB,\mC\;(m\times n) : (\mA \pm
\mB) \pm \mC = \mA \pm (\mB \pm \mC)$ 
  
\item \hil{Multiplication by a scalar:} $\mA\;(m \times n),\;c$ a scalar $c\mA = [c\cdot a_{ij}]\;(m \times
n)$

\item \hil{Matrix multiplication} or matrix product: $\mA \; (m \times
n),\; \mB\;(n \times p)$
\[
  \mA\mB_{ij}=\sum_{k=1}^na_{ik}b_{kj}\;\;\forall\;i=1,\ldots,m;\;j=1,\ldots,p\;(m \times p) 
\]
If the blocks are conformable, multiplication of partitioned matrices proceeds analogously.

\end{enumerate}
\enddefn


## Rules

\prop\zlabel{rules1}
\begin{enumerate}
\item\zlabel{it:19.1} $\mA\;(m \times n)$ : $\mI_m\mA = \mA\mI_n=\mA$

\item\zlabel{it:19.2} $\mA\; (m\times n),\mB,\mC\;(n \times r)$ : $\mA(\mB \pm \mC) = \mA\mB \pm \mA\mC$

\item\zlabel{it:19.3} $\mA\;(m\times n),\mB,\mC \;(p\times q)$ : $\mA \otimes (\mB \pm \mC) = \mA \otimes \mB \pm \mA \otimes \mC$

\item\zlabel{it:19.4} $\mA,\mB\;(m\times n)$ : $(\mA\pm \mB)^\top = \mA^\top\pm \mB^\top$

\item\zlabel{it:19.5} $\mA, \mB\; (m \times m)$ : $\tr(\mA \pm \mB) = \tr(\mA)\pm \tr(\mB)$

\item\zlabel{it:19.6} $\mA, \mB\; (m \times n)$ : $\rk(\mA \pm \mB) \leqslant \rk(\mA) + \rk(\mB)$

\item\zlabel{it:19.7} $\mA\;(m\times n),\mB\;(n\times p)$ : $\rk(\mA\mB) \leqslant \min(\rk(\mA),\rk(\mB))$

\item\zlabel{it:19.8} $\mA \;(m \times m)$ : $\mA + \mA^\top$ is a symmetric $(m \times m)$ matrix

\end{enumerate}
\endprop


## Rules (2)

\prop\zlabel{rules2}
\begin{enumerate}
\item\zlabel{it:20.1} $(\mA\mB)\mC = \mA(\mB\mC) = \mA\mB\mC$

\item\zlabel{it:20.2} $\mA\mB \neq \mB\mA$ in general

\item\zlabel{it:20.3}  $\mA\;(m \times n), \mB\;(p\times q),\mC\;(n\times r),\mD\;(q \times s) : (\mA \otimes \mB)(\mC \otimes \mD) = \mA\mC\otimes \mB\mD$.

\item\zlabel{it:20.4} $(\mA\mB)^\top = \mB^\top \mA^\top$
    
\item\zlabel{it:20.5} $(\mA\mB)^{-1}= \mB^{-1}\mA^{-1}$

\item\zlabel{it:20.6} $\mA\;(m \times n), \mB\;(n \times m) : \tr(\mA\mB)= \tr(\mB\mA)$\\
This holds more generally for any cyclical permutation of matrices $\mA_1,\ldots,\mA_n$ such that the product remains defined. 

\item\zlabel{it:20.7} $\mA,\mB\;(m \times m) : \det(\mA\mB) = \det(\mA)\det(\mB)$

\item\zlabel{it:20.8} $\mA\;(m \times n):\rk(\mA)=\rk(\mA^\top)=\rk(\mA^\top\mA)=\rk(\mA\mA^\top)$

\item\zlabel{it:20.9} $\mA\;(m\times n)$: $\mA^\top \mA$ and $\mA\mA^\top$ are symmetric positive semidefinite.\\
If, furthermore, $\rk(\mA)=n$, then $\mA^\top \mA$ is positive definite.

\end{enumerate}
\endprop



## Rules (3)

\prop\zlabel{rules3}
For square $\mA\; (m\times m)$ the following hold:
\begin{enumerate}
 \item\zlabel{it:21.1} $\tr(\mA^\top) = \tr(\mA)$
 
 \item\zlabel{it:21.2} $\det(\mA^\top) = \det(\mA)$ 
 
 \item\zlabel{it:21.3} $(\mA^\top)^{-1} = (\mA^{-1})^\top$, if $\mA$ is nonsingular. 

  \item\zlabel{it:21.4} $\det(\mA^{-1})= 1/\det(\mA)$ 
  
  \item\zlabel{it:21.5} $\lambda$ is eigenvalue of $\mA$ with eigenvector $\vv$ $\Rightarrow$ $1/\lambda$ is an eigenvalue of $\mA^{-1}$ with eigenvector $\vv$.

  \item\zlabel{it:21.6} $ \rk(\mA) = m \Leftrightarrow \mA^{-1}$ exists
    
  \item\zlabel{it:21.7} $\rk(\mA) =m \Rightarrow \mA^+ = \mA^{-1}$

\end{enumerate}
\endprop


## Orthogonal Matrices

\prop
$\mA$ is orthogonal $\Leftrightarrow$
\begin{enumerate}
 \item\zlabel{it:22.1}  $\mA\mA^\top = \mI_m \Leftrightarrow \mA^\top \mA = \mI_m$. 
 
 \item\zlabel{it:22.2} $\mA^\top$ is orthogonal. 

\item\zlabel{it:22.3} $\mA^{-1}$ is orthogonal.
\end{enumerate}
\endprop


## Partitioned Inverses

\prop\zlabel{partitionedinverses}
$\mA\;(m \times m), \mB\;(m \times n), \mC\;(n \times m), \mD\;(n \times n)$ :
\[
\left(%
\begin{array}{cc}
  \mA & \mB \\
  \mC & \mD \\
\end{array}%
\right)^{-1}=\hspace{8cm}\]\[\left(%
\begin{array}{cc}
  \mA^{-1} + \mA^{-1}\mB(\mD-\mC\mA^{-1}\mB)^{-1}\mC\mA^{-1}
 & -\mA^{-1}\mB(\mD-\mC\mA^{-1}\mB)   \\
  -(\mD-\mC\mA^{-1}\mB)^{-1}\mC\mA^{-1}  & (\mD-\mC\mA^{-1}\mB)^{-1} \\
\end{array}%
\right),
\]
provided the respective inverses exist.
\endprop


## Partitioned Inverses

\prop
For nonsingular $\mA_i\;(m_i \times m_i)$, $i = 1,\ldots, r$:
\[
\left(%
\begin{array}{ccc}
  \mA_1 &  & \mZeros \\
   & \ddots &  \\
  \mZeros &  & \mA_r \\
\end{array}%
\right)^{-1}=\left(%
\begin{array}{ccc}
  \mA_1^{-1} &  &0 \\
   & \ddots &  \\
  0 &  & \mA_r^{-1} \\
\end{array}%
\right)
\]
\endprop



## Relationship Between the Properties

\prop
\begin{enumerate}
\item\zlabel{it:25.1} $\mB$ is nonsingular $\Rightarrow\ \det(\mB\mA\mB^{-1}) = \det(\mA)$

\item\zlabel{it:25.2} $\det(\mI_m) = 1$

\item\zlabel{it:25.3} $\mA\;(m \times m)$ with eigenvalues $\lambda_1,\ldots,\lambda_m : \det(\mA) =\prod_{j=1}^m
\lambda_j$

\item\zlabel{it:25.4} $\mA\;(m \times m) : \rk(\mA) < m\ \Leftrightarrow\ \det(\mA) = 0$

\item\zlabel{it:25.5} $\rk(\mA)=m\ \Leftrightarrow\ \det(\mA) \neq 0$

\item\zlabel{it:25.6} $\mA$ is singular $\Leftrightarrow\ \det(\mA) = 0$

\item\zlabel{it:25.7} If $\mA$ and $\mD$ are square, then 
\[
\left|%
\begin{array}{cc}
  \mA & \mB \\
  0 & \mD \\
\end{array}%
\right|=|\mA||\mD|
\] 

\item\zlabel{it:25.8} If $\mA$ and $\mD$ are square and $\mA^{-1}$ exists, then 
\[
\left|%
\begin{array}{cc}
  \mA & \mB \\
  \mC & \mD \\
\end{array}%
\right|=|\mA||\mD-\mC\mA^{-1}\mB|
\]
\end{enumerate}
\endprop


## Relationship Between the Properties

\prop\label{propsidempotent}\zlabel{propsidempotent}
For idempotent $\mA \;(m \times m)$:
\begin{enumerate} 
\item\zlabel{it:26.1} $\rk(\mA) = m\ \Rightarrow\ \mA = \mI_m$

\item\zlabel{it:26.2} $\rk(\mA) = \tr(\mA)$

\item\zlabel{it:26.3} $\rk(\mI_m-\mA) = m-\rk(\mA)$
\end{enumerate}
\endprop



## Relationship Between the Properties

\prop\zlabel{relprop3}
For square $\mA\;(m \times m)$:
\begin{enumerate}
 \item\zlabel{it:27.1} $\mA = \diag(a_{11},\ldots,a_{mm}) \Rightarrow
a_{11},\ldots,a_{mm}$ are the eigenvalues of $\mA$.\\
In fact, triangularity of $\mA$ suffices. 

\item\zlabel{it:27.2} $\mA$ is symmetric $\Rightarrow$ all eigenvalues of $\mA$ are real numbers. 

\item\zlabel{it:27.3} $\mA$ is idempotent $\Rightarrow$ all eigenvalues of $\mA$ are 0 or 1.

\item\zlabel{it:27.4} $\mA$ is singular $\Leftrightarrow$ 0 is an eigenvalue of $\mA$.

\item\zlabel{it:27.5} $\mA$ is nonsingular $\Leftrightarrow$ all eigenvalues of $\mA$ are nonzero.
 
\item\zlabel{it:27.6} $\mA$ symmetric: $\mA$ is positive definite $\Leftrightarrow$ all eigenvalues of $\mA$
are real and greater than 0. 

\item\zlabel{it:27.7} $\mA$ symmetric: $\mA$ is positive semidefinite $\Leftrightarrow$ all eigenvalues of $\mA$ are real and greater than or equal to 0. 

\item\zlabel{it:27.8} $\mA$ has eigenvalues $\lambda_1,\ldots,\lambda_m : \tr(\mA) = \sum_{j=1}^m\lambda_j$.\note{Proof goes by Schur decomposition of a square matrix and flipping the trace, see L\"utkepohl, 5.2.3(2)}
\end{enumerate}
\endprop


## Relationship Between the Properties

\prop\zlabel{prop:pd and det}
$\mA$ positive (semi) definite $\Leftrightarrow$
\[ 
\det\left(\begin{array}{ccc}
  a_{11} & \cdots & a_{1i} \\
  \vdots & \ddots & \vdots \\
  a_{i1} & \cdots & a_{ii}
\end{array}%
\right)>0\;(\geqslant 0)\;\;\textrm{ for } i = 1,\ldots,m.
\] 
$\mA$ negative (semi) definite $\Leftrightarrow$ 
\[
\det\left(\begin{array}{ccc}
  a_{11} & \cdots & a_{1i} \\
  \vdots & \ddots & \vdots \\
  a_{i1} & \cdots & a_{ii}
\end{array}%
\right)\begin{cases}>0\;(\geqslant 0) &i \textrm{
even}\\<0\;(\leqslant 0) &i \textrm{ odd}\end{cases}\;\;\textrm{
for } i = 1,\ldots,m.
\]
\endprop


## Spectral Decomposition of a Symmetric Matrix

\thmn\zlabel{spectraldecomp}
Let $\mA\;(m \times m)$ be symmetric with eigenvalues $\lambda_1,\ldots,\lambda_m$. Then, 
\[ 
  \mA= \mU\mLambda \mU^\top,
\]
where $\mLambda = \diag(\lambda_1,\ldots,\lambda_m)$ and $\mU$ is the real orthogonal $(m \times m)$ matrix whose columns are the orthonormal eigenvectors $\vv_1,\ldots,\vv_m$ of $\mA$ (i.e.\ $\vv_i^\top\vv_j=1$ if $i=j$ and $0$ else) associated with $\lambda_1,\ldots,\lambda_m$. 
In other ``words,''
\[
  \mA=\sum_{j=1}^m\lambda_j\vv_j\vv_j^\top.
\]
\endthmn


## Cholesky Decomposition

\thmn\label{cholesky}\zlabel{cholesky}
$\mA\;(m \times m)$ symmetric positive definite:

There exists a unique lower (upper) triangular $(m \times m)$ matrix $\mB$ with real positive diagonal elements such that $\mA = \mB\mB^\top$.
\endthmn

\xmpl $\mA\;(2\times 2)$

\begin{eqnarray*}
\left(%
\begin{array}{cc}
  a_{11} & a_{12} \\
  a_{12} & a_{22} \\
\end{array}%
\right)&=&\left(%
\begin{array}{cc}
  b_{11} & 0 \\
  b_{12} & b_{22} \\
\end{array}%
\right)\left(%
\begin{array}{cc}
  b_{11} & b_{12} \\
  0 & b_{22} \\
\end{array}%
\right) \Rightarrow \\[.5cm]
b_{11}&=&\sqrt{a_{11}},\\b_{12}&=&a_{12}/b_{11},\\b_{22}&=&\sqrt{a_{22}-b_{12}^2}.
\end{eqnarray*}
\endxmpl


## Matrix Calculus


Let $f(\vx)$ be a differentiable real-valued function of the $(m \times 1)$ vector $\vx = (x_1,\ldots,x_m)^\top$.

\defn[Gradient]\zlabel{def:Gradient}
The \hil{gradient} of $f(\cdot)$ is
\[
  \frac{\partial f}{\partial \vx}:=\left(%
\begin{array}{c}
  \frac{\partial f}{\partial x_1} \\
  \vdots \\
  \frac{\partial f}{\partial x_m} \\
\end{array}%
\right)\;\;(m\times 1)
\] 
and
\[
  \frac{\partial f}{\partial \vx^\top}:=\left(
  \frac{\partial f}{\partial x_1} , \cdots , \frac{\partial f}{\partial x_m}\right)\;\;(1\times m)
\]
\enddefn



## Matrix Calculus

\defn[Hessian]
The \hil{Hessian} of $f(\cdot)$ is
\[
  \frac{\partial^2 f}{\partial \vx\partial \vx^\top}:=\left(%
\begin{array}{ccc}
  \frac{\partial^2 f}{\partial x_1\partial x_1}&\cdots&\frac{\partial^2 f}{\partial x_1\partial x_m} \\
  \vdots &\ddots&\vdots\\
  \frac{\partial^2 f}{\partial x_m\partial x_1}&\cdots&\frac{\partial^2 f}{\partial x_m\partial x_m}\\
\end{array}%
\right)\;\;(m\times m)
\]
\enddefn



## Matrix Calculus

\defn[Jacobian]
Let $\vy(\vx)=(y_1(\vx),\ldots, y_n(\vx))^\top$ be an  $(n \times 1)$ vector of differentiable functions of the $(m \times 1)$ vector $\vx= (x_1,\ldots, x_m)^\top$.
That is, $\vy$ is a function mapping a subset of $\mathbb{R}^m$ on a subset of $\mathbb{R}^n$.\medskip

The \hil{Jacobian} of $\vy(\cdot)$ is defined as
\[
  \frac{\partial \vy}{\partial \vx^\top}:=\left(%
\begin{array}{ccc}
  \frac{\partial y_1}{\partial x_1}&\cdots&\frac{\partial y_1}{\partial x_m} \\
  \vdots &\ddots&\vdots\\
  \frac{\partial y_n}{\partial x_1}&\cdots&\frac{\partial y_n}{\partial x_m}\\
\end{array}%
\right)\;\;(n\times m)
\]
\enddefn


## Matrix Calculus

\prop\zlabel{matrdiff}
We have
\begin{enumerate}
\item $\vx,\;\va\;(m \times 1)$ \[\frac{\partial \va^\top \vx}{\partial \vx}=\va\] 

\item  $\vx\; (m \times 1),\;\mA\;(m \times m)$
\[
  \frac{\partial \vx^\top \mA \vx}{\partial \vx}=(\mA+\mA^\top)\vx
\] 
(Note how the formula simplifies if $\mA$ is symmetric.)

\item
\[
  \frac{\partial^2 \vx^\top \mA \vx}{\partial \vx\partial \vx^\top}=(\mA+\mA^\top)
\]
\end{enumerate}
\endprop


